version: '3'

services:
  darwin-beagle-framework:
    image: ${DOCKER_REGISTRY_URL}/darwin-beagle-framework:builder
    volumes:
      - .:/home/application
    working_dir: /home/application
    command: ["/home/application/run-ci.sh"]

#ci-compose
