name: Beagle Android CI

on:
    push:
        tags:
            - '*'
jobs:
    generate-release:
        name: Generate release
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Install NDK
              run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
            - name: Set up Ruby 2.7.1
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: 2.7.1
            - name: Install Fastlane
              run: bundle install
            - name: Deploy new version
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: bundle exec fastlane deploy_new_version
        