name: Beagle Android CI

on:
    push:
jobs:
    generate-release:
        name: Generate release
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Install SDK
              uses: malinskiy/action-android/install-sdk@release/0.0.5
            - run: adb devices
            - run: echo $ANDROID_HOME
            - name: Android NDK toolchain Setup
              uses: ravinderjangra/android-ndk-toolchain-setup@0.1
            - name: Set up Ruby 2.7.1
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: 2.7.1
            - name: Install Fastlane
              run: bundle install
            - name: Deploy new version
              env:
                REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
                NAME_REPO_TOKEN: ${{ secrets.NAME_REPO_TOKEN }}
                NX_USR_SNP: ${{ secrets.NX_USR_SNP }}
                NX_PSS_SNP: ${{ secrets.NX_PSS_SNP }}
                NX_REPO_URL: ${{ secrets.NX_REPO_URL }}
              run: bundle exec fastlane deploy_new_version
        